pipeline {
    // Do not run control job on master.
    agent { label 'docker' }

    stages {
        stage('GIT') {
            steps {

                echo "BUILD NUMBER IS ${TEAMFORGE_CORE_BUILD_VERSION}"
                echo "BUILD NUMBER IS ${env.TEAMFORGE_CORE_BUILD_VERSION}"
                checkout scm
            }
        }
    }
}