pipeline {
    // Do not run control job on master.
    agent { label 'docker' }

    stages {
        stage('Setup TeamForge app') {

            agent {
                docker {
                    image 'rakcheru/python-2-7-slim-git:1'
                }
            }
            steps {
                // This step actually install TeamForge and get te URL for following stages
                sh "python jenkins-python-server/hello-server.py"
            }
        }
        stage('GIT') {

            agent {
                docker {
                    image 'rakcheru/python-2-7-slim-git:1'
                }
            }
            steps {
                echo "BUILD NUMBER IS ${TEAMFORGE_CORE_BUILD_VERSION}"
                echo "BUILD NUMBER IS ${env.TEAMFORGE_CORE_BUILD_VERSION}"
                checkout scm
            }
        }
    }
}